### ISSUE TITLE
win10检测到病毒？

### ISSUE THREAD

**Issue by xiongjy2104** [hxz393/BrutalityExtractor#1]
看有人推荐，想适用下，下载后报这个：
Program:Win32/Wacapew.C!ml
已删除

**Comment by hxz393** [comment]
请问你的系统版本是什么？我这里用的火绒，自带防火墙没开启。

**Comment by hxz393** [comment]
刚使用一台全新安装，打上最新补丁的 Win10，测试打开软件没有问题。
搜了一下这个病毒 Program:Win32/Wacapew.C!ml 兄弟你的电脑怕是很危险了，赶紧下个火绒全盘杀毒。

**Comment by 805333** [comment]
批量解压有点问题呢 是不包含子目录么

**Comment by hxz393** [comment]
> 批量解压有点问题呢 是不包含子目录么

子目录下压缩文件也解压，如果压缩文件本身没问题，那你碰到的问题是什么？
